version: 1.0.{build}
image: Ubuntu

max_jobs: 1

init:
  - echo Init step
  
install:
  - echo Install step

build_script:
  - echo Build step
  - cd Lab1
  # - sh : rebuild.sh
  - cd ..
  
test_script:
  - echo Test step
  # - sh : ./
  
on_success:
  - echo SUCCESS
  
on_failure:
  - echo EPIC FAIL
