version: 1.0.{build}
image: Ubuntu

max_jobs: 1

init:
  - echo Init step
  
install:
  - echo Install step

build_script:
  - echo Build step
  - cd Lab1
  - sh rebuild.sh
  - sleep 10
  - cd ..
  
test_script:
  - echo Test step
  - docker ps -a
  - cd Lab1
  - cd client
  #- go run clientTests.go
  - sleep 30
  - docker ps -a
  - go run clientTests.go
  - cd ..
  - cd ..
  
on_success:
  - echo SUCCESS
  
on_failure:
  - echo EPIC FAIL
